// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Auction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AvailabilityId")
                        .HasColumnType("integer")
                        .HasColumnName("availability_id");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_utc");

                    b.Property<Guid?>("CurrentHighBidId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_high_bid_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("description");

                    b.Property<DateTime>("EndsUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_utc");

                    b.Property<string>("ItemTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("item_title");

                    b.Property<decimal>("MinIncrement")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("min_increment");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<decimal>("ReserveMinPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("reserve_min_price");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.Property<Guid>("SellerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("seller_user_id");

                    b.Property<decimal>("StartingPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("starting_price");

                    b.Property<DateTime>("StartsUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_utc");

                    b.Property<int>("StateId")
                        .HasColumnType("integer")
                        .HasColumnName("state_id");

                    b.HasKey("Id")
                        .HasName("pk_auctions");

                    b.HasIndex("CurrentHighBidId")
                        .IsUnique()
                        .HasDatabaseName("ix_auctions_current_high_bid_id");

                    b.HasIndex("SellerUserId")
                        .HasDatabaseName("ix_auctions_seller_user_id");

                    b.HasIndex("OrgId", "AvailabilityId", "CreatedUtc", "Id")
                        .IsDescending(false, false, true, true)
                        .HasDatabaseName("IX_Auctions_Listing_Pagination");

                    b.ToTable("auctions", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.AuctionAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<int>("AfterStateId")
                        .HasColumnType("integer")
                        .HasColumnName("after_state_id");

                    b.Property<Guid>("AuctionId")
                        .HasColumnType("uuid")
                        .HasColumnName("auction_id");

                    b.Property<int>("BeforeStateId")
                        .HasColumnType("integer")
                        .HasColumnName("before_state_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("reason");

                    b.HasKey("Id")
                        .HasName("pk_auction_audit_logs");

                    b.HasIndex("ActorUserId")
                        .HasDatabaseName("ix_auction_audit_logs_actor_user_id");

                    b.HasIndex("AuctionId", "Id")
                        .HasDatabaseName("ix_auction_audit_logs_auction_id_id");

                    b.ToTable("auction_audit_logs", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.AuctionState_Tr", b =>
                {
                    b.Property<int>("StateId")
                        .HasColumnType("integer")
                        .HasColumnName("state_id");

                    b.Property<string>("Language")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("language");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("StateId", "Language")
                        .HasName("pk_auction_states");

                    b.ToTable("auction_states", (string)null);

                    b.HasData(
                        new
                        {
                            StateId = 1,
                            Language = "en",
                            Name = "Draft"
                        },
                        new
                        {
                            StateId = 1,
                            Language = "ar",
                            Name = "مسودة"
                        },
                        new
                        {
                            StateId = 2,
                            Language = "en",
                            Name = "Scheduled"
                        },
                        new
                        {
                            StateId = 2,
                            Language = "ar",
                            Name = "مجدول"
                        },
                        new
                        {
                            StateId = 3,
                            Language = "en",
                            Name = "Live"
                        },
                        new
                        {
                            StateId = 3,
                            Language = "ar",
                            Name = "نشط"
                        },
                        new
                        {
                            StateId = 4,
                            Language = "en",
                            Name = "Closed"
                        },
                        new
                        {
                            StateId = 4,
                            Language = "ar",
                            Name = "مغلق"
                        },
                        new
                        {
                            StateId = 5,
                            Language = "en",
                            Name = "Settled"
                        },
                        new
                        {
                            StateId = 5,
                            Language = "ar",
                            Name = "تمت التسوية"
                        },
                        new
                        {
                            StateId = 6,
                            Language = "en",
                            Name = "Cancelled"
                        },
                        new
                        {
                            StateId = 6,
                            Language = "ar",
                            Name = "ملغى"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Bid", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<Guid>("AuctionId")
                        .HasColumnType("uuid")
                        .HasColumnName("auction_id");

                    b.Property<int>("AvailabilityId")
                        .HasColumnType("integer")
                        .HasColumnName("availability_id");

                    b.Property<Guid>("BidderUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("bidder_user_id");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_utc");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("idempotency_key");

                    b.Property<DateTime>("PlacedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("placed_utc");

                    b.Property<string>("RejectReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("reject_reason");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.Property<int>("StateId")
                        .HasColumnType("integer")
                        .HasColumnName("state_id");

                    b.HasKey("Id")
                        .HasName("pk_bids");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ix_bids_idempotency_key");

                    b.HasIndex("BidderUserId", "PlacedUtc")
                        .HasDatabaseName("ix_bids_bidder_user_id_placed_utc");

                    b.HasIndex("AuctionId", "AvailabilityId", "Amount", "PlacedUtc")
                        .IsDescending(false, false, true, false)
                        .HasDatabaseName("IX_Bids_Leaderboard_Amount");

                    b.ToTable("bids", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.BidState_Tr", b =>
                {
                    b.Property<int>("StateId")
                        .HasColumnType("integer")
                        .HasColumnName("state_id");

                    b.Property<string>("Language")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("language");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("StateId", "Language")
                        .HasName("pk_bid_states");

                    b.ToTable("bid_states", (string)null);

                    b.HasData(
                        new
                        {
                            StateId = 1,
                            Language = "en",
                            Name = "Accepted"
                        },
                        new
                        {
                            StateId = 1,
                            Language = "ar",
                            Name = "مقبول"
                        },
                        new
                        {
                            StateId = 2,
                            Language = "en",
                            Name = "Rejected"
                        },
                        new
                        {
                            StateId = 2,
                            Language = "ar",
                            Name = "مرفوض"
                        },
                        new
                        {
                            StateId = 3,
                            Language = "en",
                            Name = "Outbid"
                        },
                        new
                        {
                            StateId = 3,
                            Language = "ar",
                            Name = "تم تجاوزه"
                        },
                        new
                        {
                            StateId = 4,
                            Language = "en",
                            Name = "Winning"
                        },
                        new
                        {
                            StateId = 4,
                            Language = "ar",
                            Name = "فائز"
                        });
                });

            modelBuilder.Entity("Domain.Entities.IdempotencyRecord", b =>
                {
                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("idempotency_key");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_utc");

                    b.Property<string>("ResponseBodyJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("response_body_json");

                    b.Property<int>("StatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("status_code");

                    b.HasKey("IdempotencyKey", "UserId")
                        .HasName("pk_idempotency_records");

                    b.ToTable("idempotency_records", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AvailabilityId")
                        .HasColumnType("integer")
                        .HasColumnName("availability_id");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_utc");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.HasKey("Id")
                        .HasName("pk_organizations");

                    b.ToTable("organizations", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<DateTime>("OccurredUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_utc");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<DateTime?>("ProcessedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_utc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("OccurredUtc")
                        .HasDatabaseName("ix_outbox_messages_occurred_utc")
                        .HasFilter("\"processed_utc\" IS NULL");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AvailabilityId")
                        .HasColumnType("integer")
                        .HasColumnName("availability_id");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_utc");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password_hash");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("OrgId")
                        .HasDatabaseName("ix_users_org_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Auction", b =>
                {
                    b.HasOne("Domain.Entities.Bid", "CurrentHighBid")
                        .WithOne()
                        .HasForeignKey("Domain.Entities.Auction", "CurrentHighBidId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_auctions_bids_current_high_bid_id");

                    b.HasOne("Domain.Entities.Organization", "Organization")
                        .WithMany("Auctions")
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_auctions_organizations_org_id");

                    b.HasOne("Domain.Entities.User", "Seller")
                        .WithMany("Auctions")
                        .HasForeignKey("SellerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_auctions_users_seller_user_id");

                    b.Navigation("CurrentHighBid");

                    b.Navigation("Organization");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("Domain.Entities.AuctionAuditLog", b =>
                {
                    b.HasOne("Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_auction_audit_logs_users_actor_user_id");

                    b.HasOne("Domain.Entities.Auction", "Auction")
                        .WithMany()
                        .HasForeignKey("AuctionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_auction_audit_logs_auctions_auction_id");

                    b.Navigation("Auction");
                });

            modelBuilder.Entity("Domain.Entities.Bid", b =>
                {
                    b.HasOne("Domain.Entities.Auction", "Auction")
                        .WithMany("Bids")
                        .HasForeignKey("AuctionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bids_auctions_auction_id");

                    b.HasOne("Domain.Entities.User", "Bidder")
                        .WithMany()
                        .HasForeignKey("BidderUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bids_users_bidder_user_id");

                    b.Navigation("Auction");

                    b.Navigation("Bidder");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.HasOne("Domain.Entities.Organization", "Organization")
                        .WithMany("Users")
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_users_organizations_org_id");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Domain.Entities.Auction", b =>
                {
                    b.Navigation("Bids");
                });

            modelBuilder.Entity("Domain.Entities.Organization", b =>
                {
                    b.Navigation("Auctions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Navigation("Auctions");
                });
#pragma warning restore 612, 618
        }
    }
}
